# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-config
  description: This component is responsible for configuring AWS Config
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component



